server.port=8081
custom.message=Salut1
resilience4j.circuitbreaker.instances.customerService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.customerService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.customerService.waitDurationInOpenState=10s

